Repository kheina-com/Blue-Blocker, pull requests merged in 2024-10, with the labels that each got.

#344 Add intercepting sidebar recommendations
  package-lock.json
  package.json
  src/content/index.ts
  src/global.d.ts
  src/injected/inject.ts
  src/manifest.ts
  src/parsers/user.ts
Labels: enhancement

#352 [chore] add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#308 Update makefile to add a comment about usage
  .github/workflows/release.yml
  makefile
Labels: documentation, question

#328 create a new CI workflow, and update some of the existing ones
  .github/CODEOWNERS
  .github/workflows/ci-main.yml
  .github/workflows/codeql.yml
  .github/workflows/njsscan.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  tsconfig.json
  yarn.lock
Labels: help wanted

#364 Update firefox release action
  .github/workflows/release.yml
Labels: dependencies

#366 [fix] Dynamic URL fix
  .github/workflows/ci-main.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  readme.md
  src/manifest.ts
  yarn.lock
Labels: bug

#368 Remove equivalent paths from zip command, exclude editor config, add source zipping to
  .github/workflows/ci-main.yml
  .github/workflows/release.yml
Labels: bug, meta
