Repository kheina-com/Blue-Blocker, pull requests merged in 2024-09, with the labels that each got.

#325 Add a description of how data is processed to the privacy policy
  privacy.md
Labels: documentation

#333 Document `jq` dependency in readme.md
  readme.md
Labels: documentation

#338 Add scraping of UserByScreenName API endpoint
  package-lock.json
  package.json
  src/content/index.ts
  src/injected/inject.ts
  src/manifest.ts
  src/parsers/user.ts
Labels: enhancement

#336 Soupcan migration
  src/background/index.ts
  src/content/index.ts
  src/pages/history/index.ts
  src/pages/integrations/index.ts
  src/pages/queue/index.ts
  src/pages/safelist/index.ts
  src/parsers/instructions.ts
  src/popup/index.html
  src/popup/index.ts
  src/shared.ts
  src/utilities.ts
Labels: bug
